name: Build GUI exe with Pyinstaller

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to use for the release'
        required: true
        type: string

jobs:
  build:

    runs-on: windows-latest

    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v3

      - name: Package Application
        run: ./build.bat

      - name: Delete existing, if any
        continue-on-error: true
        run: |
          gh release delete ${{ inputs.tag }} --cleanup-tag -y

      - name: Create release
        run: |
          gh release create ${{ inputs.tag }} --generate-notes

      - name: Upload executables
        run: |
          cd dist
          gh release upload ${{ inputs.tag }} $(Get-ChildItem . -name)
